---
- name: Create RKE2 directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ rke2_agent_config_dir }}"
    - "{{ rke2_data_dir }}"

- name: Download RKE2 installation script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0755'

- name: Install RKE2 agent
  shell: |
    INSTALL_RKE2_VERSION={{ rke2_version }} \
    INSTALL_RKE2_CHANNEL={{ rke2_channel }} \
    INSTALL_RKE2_METHOD={{ rke2_method }} \
    INSTALL_RKE2_TYPE=agent \
    /tmp/rke2-install.sh
  args:
    creates: /usr/local/bin/rke2

- name: Create RKE2 agent config file
  template:
    src: agent-config.yaml.j2
    dest: "{{ rke2_agent_config_file }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart rke2-agent

- name: Create systemd service file for RKE2 agent
  copy:
    src: /usr/local/lib/systemd/system/rke2-agent.service
    dest: /etc/systemd/system/rke2-agent.service
    remote_src: yes
  notify:
    - reload systemd
    - restart rke2-agent

- name: Enable and start RKE2 agent service
  systemd:
    name: rke2-agent
    enabled: yes
    state: started
    daemon_reload: yes